greeting:
  message: Welcome to the Simple E-Commerce.

server:
  port: 0

spring:
  application:
    name: owo-member

  profiles:
    active: member

  cloud:
    config:
      name: ecommerce

  config:
    import: optional:configserver:http://127.0.0.1:8888

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

oauth:
  info:
    kakao:
      client-id: e26484aed3a35f2f7769c5a422c1120e
      client-secret: DICBCEo1WyYjYDcb5zwc6GYIcFuAlfI7
      redirect: http://127.0.0.1:8000/oauth/kakao/callback
      url:
        login: https://kauth.kakao.com/oauth/authorize
        token: https://kauth.kakao.com/oauth/token
        profile: https://kapi.kakao.com/v2/user/me

    google:
      client-id: cli-id
      client-secret: cli-secret
      redirect: redi
      url:
        login: https://accounts.google.com/o/oauth2/v2/auth
        token: https://oauth2.googleapis.com/token
        profile: https://www.googleapis.com/oauth2/v3/userinfo
    naver:
      client-id: SPIHVXmm4AkrmgmyMCMl
      client-secret: 3i2oX5zrW6
      redirect: http://127.0.0.1:8000/oauth/naver/login
      url:
        login: https://nid.naver.com/oauth2.0/authorize
        token: https://nid.naver.com/oauth2.0/token
        profile: https://openapi.naver.com/v1/nid/me
