server:
  port: 8761

spring:
  application:
    name: owo-discovery

eureka:
  client:
    register-with-eureka: false #eureka? registry? ??? ? ??
    fetch-registry: false       #registru? ?? ?? ??? ? ??