server:
  port: 0

spring:
  application:
    name: owo-payment

  profiles:
    active: payment

  cloud:
    config:
      name: ecommerce

  config:
    import: optional:configserver:http://127.0.0.1:8888

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
