server:
  port: 8000

#jwt:
#  secret: ADBF#!@$DAOGEB@N!%^#$%$#*@K@!GDS<M

eureka:
  instance:
    prefer-ip-address: true #Discovery? ??? ??? ?? ? IP Address? ??
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

spring:
  application:
    name: owo-gateway

  config:
    import: optional:configserver:http://127.0.0.1:8888

  cloud:
    config:
      name: ecommerce

    gateway:
      default-filters: #spring cloud gateway global filter
        - name: GlobalFilter
          args:
            baseMessage: Spring Cloud Gateway GlobalFilter
            preLogger: true
            postLogger: true
      routes: #msa routing
        - id: owo-member
          uri: lb://OWO-MEMBER  #lb => Load Balancer
          predicates:
            - Path=/owo-member/members/login
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie #Post? ?? Request Header ?? ?? ??? ??? ?? ??.
            - RewritePath=/owo-member/(?<segment>.*), /$\{segment} #?? owo-member? ???? ??? ????.
            - CustomFilter

        - id: owo-member
          uri: lb://OWO-MEMBER  #lb => Load Balancer
          predicates:
            - Path=/owo-member/members/signUp
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie #Post? ?? Request Header ?? ?? ??? ??? ?? ??.
            - RewritePath=/owo-member/(?<segment>.*), /$\{segment} #?? owo-member? ???? ??? ????.
            - CustomFilter

        - id: owo-member
          uri: lb://OWO-MEMBER  #lb => Load Balancer
          predicates:
            - Path=/owo-member/tests/**
            - Method=GET,POST
          filters:
            - RemoveRequestHeader=Cookie #Post? ?? Request Header ?? ?? ??? ??? ?? ??.
            - RewritePath=/owo-member/(?<segment>.*), /$\{segment} #?? owo-member? ???? ??? ????.
            - CustomFilter

        - id: owo-member
          uri: lb://OWO-MEMBER  #lb => Load Balancer
          predicates:
            - Path=/owo-member/members/**
            - Method=GET,PUT,DELETE
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/owo-member/(?<segment>.*), /$\{segment} #?? owo-member? ???? ??? ????.
            - JwtAuthorizationHeadersFilter

        - id: owo-member
            uri: lb://OWO-MEMBER  #lb => Load Balancer
            predicates:
              - Path=/owo-member/actuator/**
              - Method=POST,GET
            filters:
              - RemoveRequestHeader=Cookie #Post? ?? Request Header ?? ?? ??? ??? ?? ??.
              - RewritePath=/owo-member/(?<segment>.*), /$\{segment} #?? owo-member? ???? ??? ????.

        - id: owo-payment
          uri: lb://OWO-PAYMENT
          predicates:
            - Path=/owo-payment/**
          filters:
            - name: CustomFilter
            - name: LoggingFilter #???? ????? ?? ?? name ?? ??.
              args:
                baseMessage: Hi, there.
                preLogger: true
                postLogger: true